from enum import Enum

class ChatStep(str, Enum):
    INICIO = "INICIO"
    BOAS_VINDAS = "BOAS_VINDAS"
    
    CONSULTANDO_EMPRESA = "CONSULTANDO_EMPRESA"
    
    # Descoberta e navegação
    ESCOLHENDO_CATEGORIA = "ESCOLHENDO_CATEGORIA"
    ESCOLHENDO_PRODUTO = "ESCOLHENDO_PRODUTO"
    VISUALIZANDO_PRODUTO = "VISUALIZANDO_PRODUTO"

    # Manipulação de carrinho
    INSERINDO_PRODUTO_CARRINHO = "INSERINDO_PRODUTO_CARRINHO"
    REMOVENDO_PRODUTO_CARRINHO = "REMOVENDO_PRODUTO_CARRINHO"
    ATUALIZANDO_QUANTIDADE = "ATUALIZANDO_QUANTIDADE"
    CONSULTANDO_CARRINHO = "CONSULTANDO_CARRINHO"

    # Valores e condições
    CONSULTANDO_VALOR_PRODUTO = "CONSULTANDO_VALOR"
    CONSULTANDO_TAXA_ENTREGA = "CONSULTANDO_TAXA_ENTREGA"
    CONSULTANDO_PROMOCOES = "CONSULTANDO_PROMOCOES"

    # Finalização
    INSERINDO_DADOS_PESSOAIS = "INSERINDO_DADOS_PESSOAIS"
    INSERINDO_DADOS_ENTREGA = "INSERINDO_DADOS_ENTREGA"
    ESCOLHENDO_FORMA_PAGAMENTO = "ESCOLHENDO_FORMA_PAGAMENTO"
    CONFIRMANDO_PEDIDO = "CONFIRMANDO_PEDIDO"
    
    PEDIDO_CONFIRMADO = "PEDIDO_CONFIRMADO"
    PEDIDO_REALIZADO = "PEDIDO_REALIZADO"
    PEDIDO_CANCELADO = "PEDIDO_CANCELADO"
    PEDIDO_EXPIRADO = "PEDIDO_EXPIRADO"
    
    # Suporte
    FALAR_COM_ATENDENTE = "FALAR_COM_ATENDENTE"
    FALAR_COM_BOT = "FALAR_COM_BOT"

